#!/usr/bin/env python3

import argparse
import glob
import os
import sys


def filter_sam_by_first_base(sam_path, out_path):
    """
    Copy SAM headers and retain only alignments whose SEQ field
    starts with 'A'.

    SAM column 10 (index 9) contains the read sequence.

    Returns
    -------
    total_alignments : int
        Number of valid alignment records examined.

    retained_alignments : int
        Number of alignment records starting with A.
    """

    total_alignments = 0
    retained_alignments = 0

    # Write to a temporary file first so that an interrupted job
    # does not leave an apparently complete output file.
    tmp_path = out_path + ".tmp"

    with open(sam_path, "r") as sam, open(tmp_path, "w") as out:

        for line in sam:

            # Preserve SAM headers
            if line.startswith("@"):
                out.write(line)
                continue

            cols = line.rstrip("\n").split("\t")

            # Skip malformed SAM records
            if len(cols) < 11:
                continue

            total_alignments += 1

            seq = cols[9]

            # Ignore missing sequence fields
            if seq == "*":
                continue

            if seq.startswith("A"):
                out.write(line)
                retained_alignments += 1

    # Move temporary file into its final location only after
    # successful completion.
    os.replace(tmp_path, out_path)

    return total_alignments, retained_alignments


def main():

    parser = argparse.ArgumentParser(
        description=(
            "HELIOS NAD-Seq Step 05: recursively identify E. coli "
            "SAM files generated by Step 04 and retain alignments "
            "whose SEQ field starts with A."
        )
    )

    parser.add_argument(
        "input_dir",
        help=(
            "Step 04 alignment directory containing per-sample "
            "subdirectories."
        )
    )

    parser.add_argument(
        "output_dir",
        nargs="?",
        default=None,
        help=(
            "Directory for A-start-filtered SAM files. "
            "Default: <parent_of_input_dir>/Astart"
        )
    )

    args = parser.parse_args()


    # --------------------------------------------------------
    # Resolve input directory
    # --------------------------------------------------------

    input_dir = os.path.abspath(args.input_dir)

    if not os.path.isdir(input_dir):
        raise FileNotFoundError(
            f"Input alignment directory does not exist: {input_dir}"
        )


    # --------------------------------------------------------
    # Resolve output directory
    # --------------------------------------------------------

    if args.output_dir:
        output_dir = os.path.abspath(args.output_dir)
    else:
        output_dir = os.path.join(
            os.path.dirname(input_dir),
            "Astart"
        )

    os.makedirs(
        output_dir,
        exist_ok=True
    )


    print("========================================")
    print("HELIOS NAD-Seq: Step 05 - A-start filter")
    print("========================================")
    print(f"Input directory:  {input_dir}")
    print(f"Output directory: {output_dir}")
    print("========================================")


    # --------------------------------------------------------
    # Find E. coli SAM files generated by Step 04
    #
    # Expected filenames:
    #
    # *_eColi_paired.sam
    # *_eColi_R1_unpaired.sam
    # *_eColi_R2_unpaired.sam
    #
    # Step 04 stores these inside sample-specific directories,
    # therefore recursive=True is required.
    # --------------------------------------------------------

    patterns = [
        os.path.join(
            input_dir,
            "**",
            "*_eColi_paired.sam"
        ),
        os.path.join(
            input_dir,
            "**",
            "*_eColi_R1_unpaired.sam"
        ),
        os.path.join(
            input_dir,
            "**",
            "*_eColi_R2_unpaired.sam"
        )
    ]

    sam_files = []

    for pattern in patterns:
        sam_files.extend(
            glob.glob(
                pattern,
                recursive=True
            )
        )

    sam_files = sorted(
        set(sam_files)
    )


    if not sam_files:
        raise FileNotFoundError(
            "No E. coli SAM files generated by Step 04 "
            f"were found under: {input_dir}"
        )


    print(
        f"E. coli SAM files found: {len(sam_files)}"
    )
    print()


    # --------------------------------------------------------
    # Counters
    # --------------------------------------------------------

    total_all = 0
    retained_all = 0

    processed_files = 0
    skipped_files = 0


    # ========================================================
    # Process each SAM file
    # ========================================================

    for sam_path in sam_files:

        base = os.path.basename(
            sam_path
        )

        output_name = base.replace(
            ".sam",
            ".Astart.sam"
        )

        out_path = os.path.join(
            output_dir,
            output_name
        )


        print("----------------------------------------")
        print(f"Input:  {base}")


        # ----------------------------------------------------
        # Skip already completed files
        #
        # A non-empty output is considered completed.
        # ----------------------------------------------------

        if os.path.isfile(out_path) and os.path.getsize(out_path) > 0:

            print(
                f"Output already exists: {output_name}"
            )
            print("Skipping.")
            print()

            skipped_files += 1
            continue


        # ----------------------------------------------------
        # Remove stale temporary output if present
        # ----------------------------------------------------

        tmp_path = out_path + ".tmp"

        if os.path.exists(tmp_path):
            os.remove(tmp_path)


        print("Filtering reads starting with A...")


        # ----------------------------------------------------
        # Run filter
        # ----------------------------------------------------

        total, retained = filter_sam_by_first_base(
            sam_path,
            out_path
        )


        total_all += total
        retained_all += retained

        processed_files += 1


        # ----------------------------------------------------
        # Statistics
        # ----------------------------------------------------

        if total > 0:

            retained_percent = (
                retained / total
            ) * 100

        else:

            retained_percent = 0.0


        print(
            f"Total alignments:   {total}"
        )

        print(
            f"A-start alignments: {retained}"
        )

        print(
            f"Retained:           "
            f"{retained_percent:.2f}%"
        )

        print(
            f"Output:             {output_name}"
        )

        print()


    # --------------------------------------------------------
    # Overall summary
    # --------------------------------------------------------

    if total_all > 0:

        retained_all_percent = (
            retained_all / total_all
        ) * 100

    else:

        retained_all_percent = 0.0


    print("========================================")
    print("Step 05 completed.")
    print("----------------------------------------")
    print(f"SAM files processed:  {processed_files}")
    print(f"SAM files skipped:    {skipped_files}")
    print(f"Total alignments:     {total_all}")
    print(f"A-start alignments:   {retained_all}")
    print(
        f"Overall retained:     "
        f"{retained_all_percent:.2f}%"
    )
    print(f"Output directory:     {output_dir}")
    print("========================================")


if __name__ == "__main__":
    main()
