```python
#!/usr/bin/env python3

import glob
import os
import argparse


def filter_sam_by_first_base(sam_path, out_path):
    """
    Copy SAM headers and retain only alignments for which the
    first base of the SEQ field is 'A'.

    The SEQ field corresponds to column 10 of a SAM alignment.
    """

    total_alignments = 0
    retained_alignments = 0

    with open(sam_path, "r") as sam, open(out_path, "w") as out:

        for line in sam:

            # Preserve SAM headers
            if line.startswith("@"):
                out.write(line)
                continue

            cols = line.rstrip("\n").split("\t")

            # Skip malformed SAM lines
            if len(cols) < 11:
                continue

            total_alignments += 1

            seq = cols[9]

            if seq.startswith("A"):
                out.write(line)
                retained_alignments += 1

    return total_alignments, retained_alignments


def main():

    parser = argparse.ArgumentParser(
        description=(
            "Filter E. coli SAM alignments generated by Step 04 "
            "and retain reads whose SEQ field starts with A."
        )
    )

    parser.add_argument(
        "input_dir",
        help=(
            "Step 04 alignment directory containing per-sample "
            "subdirectories."
        )
    )

    parser.add_argument(
        "output_dir",
        nargs="?",
        default=None,
        help=(
            "Directory for A-start-filtered SAM files. "
            "Default: <parent_of_input_dir>/Astart"
        )
    )

    args = parser.parse_args()


    # ---------------------------------------------------------
    # Input directory
    # ---------------------------------------------------------

    input_dir = os.path.abspath(args.input_dir)

    if not os.path.isdir(input_dir):
        raise FileNotFoundError(
            f"Input alignment directory does not exist: {input_dir}"
        )


    # ---------------------------------------------------------
    # Output directory
    # ---------------------------------------------------------

    if args.output_dir:
        output_dir = os.path.abspath(args.output_dir)
    else:
        output_dir = os.path.join(
            os.path.dirname(input_dir),
            "Astart"
        )

    os.makedirs(output_dir, exist_ok=True)


    print("========================================")
    print("HELIOS NAD-Seq: Step 05 - A-start filter")
    print("========================================")
    print(f"Input directory:  {input_dir}")
    print(f"Output directory: {output_dir}")
    print("========================================")


    # ---------------------------------------------------------
    # Find E. coli SAM files recursively
    #
    # Step 04 generates:
    #   *_eColi_paired.sam
    #   *_eColi_R1_unpaired.sam
    #   *_eColi_R2_unpaired.sam
    # ---------------------------------------------------------

    pattern = os.path.join(
        input_dir,
        "**",
        "*_eColi_*.sam"
    )

    sam_files = sorted(
        glob.glob(pattern, recursive=True)
    )


    if not sam_files:
        raise FileNotFoundError(
            "No E. coli SAM files were found under "
            f"{input_dir}"
        )


    print(f"E. coli SAM files found: {len(sam_files)}")
    print()


    # ---------------------------------------------------------
    # Filter each SAM file
    # ---------------------------------------------------------

    total_all = 0
    retained_all = 0


    for sam_path in sam_files:

        base = os.path.basename(sam_path)

        output_name = base.replace(
            ".sam",
            ".Astart.sam"
        )

        out_path = os.path.join(
            output_dir,
            output_name
        )


        print(f"Processing: {base}")


        total, retained = filter_sam_by_first_base(
            sam_path,
            out_path
        )


        total_all += total
        retained_all += retained


        if total > 0:
            retained_percent = (
                retained / total
            ) * 100
        else:
            retained_percent = 0


        print(
            f"  Total alignments:    {total}"
        )

        print(
            f"  A-start alignments:  {retained}"
        )

        print(
            f"  Retained:            "
            f"{retained_percent:.2f}%"
        )

        print(
            f"  Output:              "
            f"{output_name}"
        )

        print()


    # ---------------------------------------------------------
    # Summary
    # ---------------------------------------------------------

    if total_all > 0:
        retained_all_percent = (
            retained_all / total_all
        ) * 100
    else:
        retained_all_percent = 0


    print("========================================")
    print("Step 05 completed.")
    print("----------------------------------------")
    print(f"Total alignments:    {total_all}")
    print(f"A-start alignments:  {retained_all}")
    print(
        f"Overall retained:    "
        f"{retained_all_percent:.2f}%"
    )
    print(f"Output directory:    {output_dir}")
    print("========================================")


if __name__ == "__main__":
    main()
```
