```python
#!/usr/bin/env python3

import pandas as pd
import glob
import os
import re
import argparse


# ------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------

def extract_barcode(filename):
    """
    Extract barcode from filename.

    Example:
        tp1_bc01_sample_eColi_paired.Astart.table
        -> bc01
    """
    match = re.search(r'(bc\d+)', os.path.basename(filename))
    return match.group(1) if match else None


def extract_timepoint(filename):
    """
    Extract time point from filename.

    Example:
        tp1_bc01_sample_eColi_paired.Astart.table
        -> tp1
    """
    match = re.search(r'(tp\d+)', os.path.basename(filename))
    return match.group(1) if match else None


def timepoint_sort_key(tp):
    """
    Sort tp1, tp2, ..., tp16 numerically.
    """
    match = re.search(r'\d+', tp)
    return int(match.group()) if match else 0


# ------------------------------------------------------------
# Main
# ------------------------------------------------------------

def main():

    parser = argparse.ArgumentParser(
        description=(
            "Merge featureCounts tables by time point and barcode "
            "for HELIOS NAD-Seq analysis."
        )
    )

    parser.add_argument(
        "input_dir",
        help=(
            "Directory containing featureCounts .table files "
            "generated by Step 06."
        )
    )

    parser.add_argument(
        "output_dir",
        nargs="?",
        default=None,
        help=(
            "Directory for merged count matrices. "
            "Default: <parent_of_input_dir>/count_tables"
        )
    )

    args = parser.parse_args()


    # --------------------------------------------------------
    # Input/output directories
    # --------------------------------------------------------

    input_dir = os.path.abspath(args.input_dir)

    if not os.path.isdir(input_dir):
        raise FileNotFoundError(
            f"Input directory does not exist: {input_dir}"
        )


    if args.output_dir:
        output_dir = os.path.abspath(args.output_dir)
    else:
        output_dir = os.path.join(
            os.path.dirname(input_dir),
            "count_tables"
        )


    os.makedirs(output_dir, exist_ok=True)


    print("========================================")
    print("HELIOS NAD-Seq: Step 07 - Merge counts")
    print("========================================")
    print(f"Input directory:  {input_dir}")
    print(f"Output directory: {output_dir}")
    print("========================================")


    # --------------------------------------------------------
    # Find all featureCounts tables
    # --------------------------------------------------------

    all_table_files = glob.glob(
        os.path.join(input_dir, "*.table")
    )


    if not all_table_files:
        raise FileNotFoundError(
            f"No .table files found in {input_dir}"
        )


    print(
        f"featureCounts tables found: "
        f"{len(all_table_files)}"
    )


    # --------------------------------------------------------
    # Identify available time points
    # --------------------------------------------------------

    timepoints = sorted(
        {
            extract_timepoint(file)
            for file in all_table_files
            if extract_timepoint(file) is not None
        },
        key=timepoint_sort_key
    )


    if not timepoints:
        raise RuntimeError(
            "No time-point identifiers (tp1, tp2, ...) "
            "were detected in the filenames."
        )


    print(
        "Time points detected: "
        + ", ".join(timepoints)
    )

    print()


    # ========================================================
    # Process each time point
    # ========================================================

    for tp in timepoints:

        print("----------------------------------------")
        print(f"Processing {tp}")


        # ----------------------------------------------------
        # Find files belonging to this time point
        #
        # glob.glob is intentionally used here to preserve
        # the original workflow style.
        # ----------------------------------------------------

        tp_files = glob.glob(
            os.path.join(
                input_dir,
                f"*{tp}*.table"
            )
        )


        # Separate paired and unpaired tables.
        #
        # Exclude "unpaired" from paired_files because the
        # word "unpaired" also contains "paired".
        paired_files = [
            file
            for file in glob.glob(
                os.path.join(
                    input_dir,
                    f"*{tp}*_paired*table"
                )
            )
            if "_unpaired" not in os.path.basename(file)
        ]


        unpaired_files = glob.glob(
            os.path.join(
                input_dir,
                f"*{tp}*_unpaired*table"
            )
        )


        print(
            f"  Total tables:    {len(tp_files)}"
        )

        print(
            f"  Paired tables:   {len(paired_files)}"
        )

        print(
            f"  Unpaired tables: {len(unpaired_files)}"
        )


        if not paired_files or not unpaired_files:

            print(
                f"WARNING: Skipping {tp}: "
                "missing paired or unpaired tables."
            )

            print()
            continue


        # ----------------------------------------------------
        # Group files by barcode
        # ----------------------------------------------------

        paired_map = {}
        unpaired_map = {}


        for file in paired_files:

            barcode = extract_barcode(file)

            if barcode:
                paired_map.setdefault(
                    barcode,
                    []
                ).append(file)


        for file in unpaired_files:

            barcode = extract_barcode(file)

            if barcode:
                unpaired_map.setdefault(
                    barcode,
                    []
                ).append(file)


        # ----------------------------------------------------
        # Barcodes present in both groups
        # ----------------------------------------------------

        common_barcodes = sorted(
            set(paired_map.keys()).intersection(
                unpaired_map.keys()
            )
        )


        if not common_barcodes:

            print(
                f"WARNING: Skipping {tp}: "
                "no matching barcodes found across "
                "paired and unpaired files."
            )

            print()
            continue


        print(
            "  Barcodes: "
            + ", ".join(common_barcodes)
        )


        # ----------------------------------------------------
        # Create time-point output directory
        # ----------------------------------------------------

        tp_output_dir = os.path.join(
            output_dir,
            tp
        )

        os.makedirs(
            tp_output_dir,
            exist_ok=True
        )


        # ----------------------------------------------------
        # Merge counts
        # ----------------------------------------------------

        merged_df = None


        for barcode in common_barcodes:

            all_files = (
                paired_map[barcode]
                + unpaired_map[barcode]
            )


            print(
                f"  {barcode}: merging "
                f"{len(all_files)} tables"
            )


            barcode_df = None


            for file in all_files:

                df = pd.read_csv(
                    file,
                    sep="\t",
                    comment="#",
                    header=0
                )


                # featureCounts output:
                #
                # Geneid  Chr  Start  End  Strand  Length  sample
                #
                # First column = Geneid
                # Seventh column = count

                if df.shape[1] < 7:
                    raise ValueError(
                        f"Unexpected featureCounts format: "
                        f"{file}"
                    )


                df = df.iloc[:, [0, 6]].copy()

                df.columns = [
                    "Geneid",
                    "count"
                ]


                # Ensure numeric count values
                df["count"] = pd.to_numeric(
                    df["count"],
                    errors="raise"
                )


                if barcode_df is None:

                    barcode_df = df

                else:

                    barcode_df = pd.merge(
                        barcode_df,
                        df,
                        on="Geneid",
                        how="outer",
                        suffixes=(
                            "",
                            "_new"
                        )
                    ).fillna(0)


                    barcode_df["count"] = (
                        barcode_df["count"]
                        + barcode_df["count_new"]
                    )


                    barcode_df.drop(
                        columns=["count_new"],
                        inplace=True
                    )


            # Rename count column to barcode
            barcode_df.rename(
                columns={
                    "count": barcode
                },
                inplace=True
            )


            # ------------------------------------------------
            # Add barcode to combined matrix
            # ------------------------------------------------

            if merged_df is None:

                merged_df = barcode_df

            else:

                merged_df = pd.merge(
                    merged_df,
                    barcode_df,
                    on="Geneid",
                    how="outer"
                ).fillna(0)


        # ----------------------------------------------------
        # Arrange barcode columns numerically
        # ----------------------------------------------------

        barcode_columns = sorted(
            [
                col
                for col in merged_df.columns
                if col.startswith("bc")
            ],
            key=lambda x: int(
                re.search(r'\d+', x).group()
            )
        )


        merged_df = merged_df[
            ["Geneid"] + barcode_columns
        ]


        # Convert counts to integers
        for barcode in barcode_columns:

            merged_df[barcode] = (
                merged_df[barcode]
                .astype(int)
            )


        # ----------------------------------------------------
        # Write merged matrix
        # ----------------------------------------------------

        output_filename = os.path.join(
            tp_output_dir,
            "merged_by_barcode_Astart_readCount.csv"
        )


        merged_df.to_csv(
            output_filename,
            index=False
        )


        print(
            f"  Merged table written:"
        )

        print(
            f"  {output_filename}"
        )

        print()


    print("========================================")
    print("Step 07 completed.")
    print(f"Output directory: {output_dir}")
    print("========================================")


if __name__ == "__main__":
    main()
```
