#!/usr/bin/env python3

import argparse
import os
import pickle as pkl

import numpy as np
import pandas as pd

from pydeseq2.dds import DeseqDataSet
from pydeseq2.default_inference import DefaultInference


def main():

    parser = argparse.ArgumentParser(
        description=(
            "Fit PyDESeq2 models independently for each HELIOS "
            "NAD-Seq time point."
        )
    )

    parser.add_argument(
        "input_dir",
        help=(
            "Directory generated by Step 07 containing "
            "tp1, tp2, ... subdirectories."
        )
    )

    parser.add_argument(
        "--start-tp",
        type=int,
        default=1,
        help="First time point to process. Default: 1."
    )

    parser.add_argument(
        "--end-tp",
        type=int,
        default=16,
        help="Last time point to process. Default: 16."
    )

    parser.add_argument(
        "--threads",
        type=int,
        default=8,
        help="Number of CPUs used by PyDESeq2. Default: 8."
    )

    parser.add_argument(
        "--min-total-count",
        type=int,
        default=10,
        help=(
            "Minimum total count across all samples required "
            "to retain a feature. Default: 10."
        )
    )

    args = parser.parse_args()

    input_dir = os.path.abspath(args.input_dir)

    if not os.path.isdir(input_dir):
        raise FileNotFoundError(
            f"Input directory does not exist: {input_dir}"
        )

    print("========================================")
    print("HELIOS NAD-Seq: Step 08 - PyDESeq2")
    print("========================================")
    print(f"Input directory:     {input_dir}")
    print(f"Time points:         tp{args.start_tp}-tp{args.end_tp}")
    print(f"CPUs:                {args.threads}")
    print(f"Minimum total count: {args.min_total_count}")
    print("========================================")

    inference = DefaultInference(
        n_cpus=args.threads
    )

    for tp in range(
        args.start_tp,
        args.end_tp + 1
    ):

        tp_dir = os.path.join(
            input_dir,
            f"tp{tp}"
        )

        input_csv = os.path.join(
            tp_dir,
            "merged_by_barcode_Astart_readCount.csv"
        )

        output_pkl = os.path.join(
            tp_dir,
            "merged_by_barcode_Astart_readCount_dds.pkl"
        )

        # ----------------------------------------------------
        # Skip missing time points
        # ----------------------------------------------------

        if not os.path.isfile(input_csv):

            print(
                f"[tp{tp}] Skipping: input file not found:"
            )
            print(
                f"        {input_csv}"
            )

            continue

        print()
        print("----------------------------------------")
        print(f"[tp{tp}] Processing")
        print(f"Input:  {input_csv}")

        # ----------------------------------------------------
        # Read count matrix
        # ----------------------------------------------------

        df = pd.read_csv(
            input_csv,
            index_col=0
        )

        if df.shape[1] != 8:
            raise ValueError(
                f"[tp{tp}] Expected 8 barcode samples, "
                f"found {df.shape[1]}."
            )

        # ----------------------------------------------------
        # Make sure barcode order is bc01-bc08
        # ----------------------------------------------------

        expected_barcodes = [
            f"bc{i:02d}"
            for i in range(1, 9)
        ]

        missing_barcodes = [
            bc
            for bc in expected_barcodes
            if bc not in df.columns
        ]

        if missing_barcodes:
            raise ValueError(
                f"[tp{tp}] Missing expected barcodes: "
                f"{', '.join(missing_barcodes)}"
            )

        df = df[expected_barcodes]

        # ----------------------------------------------------
        # Convert counts to numeric
        # ----------------------------------------------------

        counts = df.apply(
            pd.to_numeric,
            errors="coerce"
        )

        if counts.isna().any().any():
            raise ValueError(
                f"[tp{tp}] Non-numeric or missing values "
                "detected in count matrix."
            )

        # featureCounts produces integer read counts
        counts = counts.astype(int)

        # ----------------------------------------------------
        # Filter low-count features
        # ----------------------------------------------------

        n_before = counts.shape[0]

        keep = (
            counts.sum(axis=1)
            >= args.min_total_count
        )

        counts = counts.loc[keep]

        n_after = counts.shape[0]

        print(
            f"Features before filtering: {n_before}"
        )

        print(
            f"Features retained:         {n_after}"
        )

        if n_after == 0:
            raise ValueError(
                f"[tp{tp}] No features remain after filtering."
            )

        # ----------------------------------------------------
        # Metadata
        #
        # bc01-bc04 = positive HELIOS samples
        # bc05-bc08 = negative controls
        # ----------------------------------------------------

        metadata = pd.DataFrame(
            {
                "sample_id": expected_barcodes,
                "conditions": (
                    ["Treated"] * 4
                    + ["Control"] * 4
                )
            },
            index=expected_barcodes
        )

        # PyDESeq2 expects samples x features
        counts = counts.T

        # ----------------------------------------------------
        # Fit DESeq2 model
        # ----------------------------------------------------

        dds = DeseqDataSet(
            counts=counts,
            metadata=metadata,
            design_factors="conditions",
            refit_cooks=False,
            inference=inference
        )

        print(
            f"[tp{tp}] Fitting size factors..."
        )

        dds.fit_size_factors(
            fit_type="ratio"
        )

        print(
            f"[tp{tp}] Fitting dispersions..."
        )

        dds.fit_genewise_dispersions()
        dds.fit_dispersion_trend()
        dds.fit_dispersion_prior()
        dds.fit_MAP_dispersions()

        print(
            f"[tp{tp}] Fitting log2 fold changes..."
        )

        dds.fit_LFC()

        if dds.refit_cooks:

            dds.varm["replaced"] = np.zeros_like(
                dds.var_names,
                dtype=bool
            )

            dds.refit()

        # ----------------------------------------------------
        # Save fitted DDS
        # ----------------------------------------------------

        with open(
            output_pkl,
            "wb"
        ) as f:

            pkl.dump(
                dds,
                f
            )

        print(
            f"[tp{tp}] Saved DDS:"
        )

        print(
            f"        {output_pkl}"
        )

    print()
    print("========================================")
    print("Step 08 completed.")
    print("========================================")


if __name__ == "__main__":
    main()
