#!/usr/bin/env python3

import argparse
import os
import pickle as pkl

from pydeseq2.default_inference import DefaultInference
from pydeseq2.ds import DeseqStats


def main():

    parser = argparse.ArgumentParser(
        description=(
            "Run PyDESeq2 statistical testing for each HELIOS "
            "NAD-Seq time point using fitted DDS objects from Step 08."
        )
    )

    parser.add_argument(
        "input_dir",
        help=(
            "Directory containing tp1, tp2, ... subdirectories "
            "with *_dds.pkl files generated by Step 08."
        )
    )

    parser.add_argument(
        "--start-tp",
        type=int,
        default=1,
        help="First time point to process. Default: 1."
    )

    parser.add_argument(
        "--end-tp",
        type=int,
        default=16,
        help="Last time point to process. Default: 16."
    )

    parser.add_argument(
        "--threads",
        type=int,
        default=8,
        help="Number of CPUs used by PyDESeq2. Default: 8."
    )

    parser.add_argument(
        "--alpha",
        type=float,
        default=0.05,
        help="Significance threshold used for adjusted p-values. Default: 0.05."
    )

    args = parser.parse_args()

    input_dir = os.path.abspath(args.input_dir)

    if not os.path.isdir(input_dir):
        raise FileNotFoundError(
            f"Input directory does not exist: {input_dir}"
        )

    if args.start_tp > args.end_tp:
        raise ValueError(
            "--start-tp must be smaller than or equal to --end-tp."
        )

    if args.threads < 1:
        raise ValueError(
            "--threads must be at least 1."
        )

    if not 0 < args.alpha < 1:
        raise ValueError(
            "--alpha must be between 0 and 1."
        )

    inference = DefaultInference(
        n_cpus=args.threads
    )

    print("========================================")
    print("HELIOS NAD-Seq: Step 09 - DESeq2 stats")
    print("========================================")
    print(f"Input directory: {input_dir}")
    print(
        f"Time points:     "
        f"tp{args.start_tp}-tp{args.end_tp}"
    )
    print(f"CPUs:            {args.threads}")
    print(f"Alpha:           {args.alpha}")
    print("========================================")

    processed = 0
    skipped = 0

    for tp in range(
        args.start_tp,
        args.end_tp + 1
    ):

        tp_name = f"tp{tp}"

        tp_dir = os.path.join(
            input_dir,
            tp_name
        )

        if not os.path.isdir(tp_dir):

            print(
                f"[{tp_name}] Directory not found, skipping."
            )

            skipped += 1
            continue

        # ----------------------------------------------------
        # Find DDS object generated by Step 08
        # ----------------------------------------------------

        dds_files = sorted(
            [
                f
                for f in os.listdir(tp_dir)
                if f.endswith("_dds.pkl")
            ]
        )

        if not dds_files:

            print(
                f"[{tp_name}] No *_dds.pkl file found, skipping."
            )

            skipped += 1
            continue

        if len(dds_files) > 1:

            raise RuntimeError(
                f"[{tp_name}] More than one *_dds.pkl file found: "
                f"{dds_files}"
            )

        dds_file = dds_files[0]

        dds_path = os.path.join(
            tp_dir,
            dds_file
        )

        print()
        print("----------------------------------------")
        print(f"[{tp_name}] Loading DDS:")
        print(f"        {dds_path}")

        # ----------------------------------------------------
        # Load fitted DDS
        # ----------------------------------------------------

        with open(
            dds_path,
            "rb"
        ) as f:

            dds = pkl.load(f)

        # ----------------------------------------------------
        # Run statistical testing
        # ----------------------------------------------------

        print(
            f"[{tp_name}] Running DeseqStats..."
        )

        stat_res = DeseqStats(
            dds,
            alpha=args.alpha,
            cooks_filter=False,
            independent_filter=True,
            inference=inference
        )

        stat_res.run_wald_test()

        if stat_res.cooks_filter:
            stat_res._cooks_filtering()

        if stat_res.independent_filter:
            stat_res._independent_filtering()

        else:
            stat_res._p_value_adjustment()

        # Print PyDESeq2 summary
        stat_res.summary()

        results_df = stat_res.results_df

        # ----------------------------------------------------
        # Save results
        # ----------------------------------------------------

        output_name = dds_file.replace(
            "_dds.pkl",
            "_results.csv"
        )

        output_path = os.path.join(
            tp_dir,
            output_name
        )

        results_df.to_csv(
            output_path,
            index=True
        )

        print(
            f"[{tp_name}] Saved results:"
        )

        print(
            f"        {output_path}"
        )

        processed += 1

    print()
    print("========================================")
    print("Step 09 completed.")
    print(f"Processed time points: {processed}")
    print(f"Skipped time points:   {skipped}")
    print("========================================")


if __name__ == "__main__":
    main()
