#!/usr/bin/env python3

import argparse
import os
import pickle as pkl

from pydeseq2.default_inference import DefaultInference
from pydeseq2.ds import DeseqStats


# ============================================================
# HELIOS NAD-Seq pipeline
# Step 09: PyDESeq2 statistical testing
#
# Expected input structure from Step 08:
#
# count_tables/
# ├── intergenic/
# │   ├── tp1/
# │   │   ├── merged_by_barcode_Astart_readCount.csv
# │   │   └── merged_by_barcode_Astart_readCount_dds.pkl
# │   ├── tp2/
# │   └── ...
# │
# └── variable_3prime/
#     ├── tp1/
#     │   ├── merged_by_barcode_Astart_readCount.csv
#     │   └── merged_by_barcode_Astart_readCount_dds.pkl
#     ├── tp2/
#     └── ...
#
#
# Usage:
#
#   python scripts/09.pydeseq2_stats.py \
#       <COUNT_TABLES_DIR>
#
#
# Example:
#
#   python scripts/09.pydeseq2_stats.py \
#       /gpfs/bwfor/work/ws/hd_qp355-tae_temp/tp_workflow/count_tables
#
# ============================================================


def process_annotation(
    annotation_name,
    annotation_dir,
    start_tp,
    end_tp,
    threads,
    alpha
):
    """
    Run PyDESeq2 statistical testing independently for each
    time point within one annotation branch.
    """

    print()
    print("========================================")
    print(f"Annotation: {annotation_name}")
    print("========================================")
    print(f"Input directory: {annotation_dir}")
    print(f"Time points:     tp{start_tp}-tp{end_tp}")
    print(f"CPUs:            {threads}")
    print(f"Alpha:           {alpha}")
    print("========================================")

    inference = DefaultInference(
        n_cpus=threads
    )

    processed = 0
    skipped = 0


    for tp in range(
        start_tp,
        end_tp + 1
    ):

        tp_name = f"tp{tp}"

        tp_dir = os.path.join(
            annotation_dir,
            tp_name
        )


        # ----------------------------------------------------
        # Check time-point directory
        # ----------------------------------------------------

        if not os.path.isdir(tp_dir):

            print(
                f"[{annotation_name} / {tp_name}] "
                "Directory not found. Skipping."
            )

            skipped += 1
            continue


        # ----------------------------------------------------
        # Find DDS object generated by Step 08
        # ----------------------------------------------------

        dds_files = sorted(
            [
                filename
                for filename in os.listdir(tp_dir)
                if filename.endswith("_dds.pkl")
            ]
        )


        if not dds_files:

            print(
                f"[{annotation_name} / {tp_name}] "
                "No *_dds.pkl file found. Skipping."
            )

            skipped += 1
            continue


        if len(dds_files) > 1:

            raise RuntimeError(
                f"[{annotation_name} / {tp_name}] "
                "More than one *_dds.pkl file found: "
                f"{dds_files}"
            )


        dds_file = dds_files[0]

        dds_path = os.path.join(
            tp_dir,
            dds_file
        )


        # ----------------------------------------------------
        # Output results file
        # ----------------------------------------------------

        output_name = dds_file.replace(
            "_dds.pkl",
            "_results.csv"
        )

        output_path = os.path.join(
            tp_dir,
            output_name
        )


        # ----------------------------------------------------
        # Skip already completed results
        # ----------------------------------------------------

        if (
            os.path.isfile(output_path)
            and os.path.getsize(output_path) > 0
        ):

            print(
                f"[{annotation_name} / {tp_name}] "
                "Results already exist. Skipping:"
            )

            print(
                f"    {output_path}"
            )

            processed += 1
            continue


        print()
        print("----------------------------------------")
        print(
            f"[{annotation_name} / {tp_name}] Loading DDS:"
        )
        print(
            f"    {dds_path}"
        )


        # ----------------------------------------------------
        # Load fitted DDS object
        # ----------------------------------------------------

        with open(
            dds_path,
            "rb"
        ) as f:

            dds = pkl.load(f)


        # ----------------------------------------------------
        # Run statistical testing
        # ----------------------------------------------------

        print(
            f"[{annotation_name} / {tp_name}] "
            "Running DeseqStats..."
        )


        stat_res = DeseqStats(
            dds,
            alpha=alpha,
            cooks_filter=False,
            independent_filter=True,
            inference=inference
        )


        # ----------------------------------------------------
        # Wald test
        # ----------------------------------------------------

        stat_res.run_wald_test()


        # ----------------------------------------------------
        # Filtering / adjusted p-values
        # ----------------------------------------------------

        if stat_res.cooks_filter:

            stat_res._cooks_filtering()


        if stat_res.independent_filter:

            stat_res._independent_filtering()

        else:

            stat_res._p_value_adjustment()


        # ----------------------------------------------------
        # Print PyDESeq2 summary
        # ----------------------------------------------------

        stat_res.summary()


        results_df = stat_res.results_df


        # ----------------------------------------------------
        # Save results safely
        # ----------------------------------------------------

        tmp_output = (
            output_path
            + ".tmp"
        )


        results_df.to_csv(
            tmp_output,
            index=True
        )


        os.replace(
            tmp_output,
            output_path
        )


        print(
            f"[{annotation_name} / {tp_name}] "
            "Saved results:"
        )

        print(
            f"    {output_path}"
        )


        processed += 1


    # --------------------------------------------------------
    # Annotation summary
    # --------------------------------------------------------

    print()
    print("----------------------------------------")
    print(
        f"{annotation_name} summary"
    )
    print("----------------------------------------")

    print(
        f"Processed/existing time points: "
        f"{processed}"
    )

    print(
        f"Skipped time points:            "
        f"{skipped}"
    )


    return processed, skipped


# ============================================================
# Main
# ============================================================

def main():

    parser = argparse.ArgumentParser(
        description=(
            "HELIOS NAD-Seq Step 09: run PyDESeq2 statistical "
            "testing independently for each time point for both "
            "intergenic and variable 3' annotations."
        )
    )


    parser.add_argument(
        "input_dir",
        help=(
            "Step 08 count_tables directory containing "
            "'intergenic' and 'variable_3prime' subdirectories."
        )
    )


    parser.add_argument(
        "--start-tp",
        type=int,
        default=1,
        help=(
            "First time point to process. "
            "Default: 1."
        )
    )


    parser.add_argument(
        "--end-tp",
        type=int,
        default=16,
        help=(
            "Last time point to process. "
            "Default: 16."
        )
    )


    parser.add_argument(
        "--threads",
        type=int,
        default=8,
        help=(
            "Number of CPUs used by PyDESeq2. "
            "Default: 8."
        )
    )


    parser.add_argument(
        "--alpha",
        type=float,
        default=0.05,
        help=(
            "Significance threshold used for adjusted p-values. "
            "Default: 0.05."
        )
    )


    args = parser.parse_args()


    # --------------------------------------------------------
    # Validate general arguments
    # --------------------------------------------------------

    input_dir = os.path.abspath(
        args.input_dir
    )


    if not os.path.isdir(
        input_dir
    ):

        raise FileNotFoundError(
            f"Input directory does not exist:\n"
            f"{input_dir}"
        )


    if args.start_tp < 1:

        raise ValueError(
            "--start-tp must be >= 1."
        )


    if args.end_tp < args.start_tp:

        raise ValueError(
            "--end-tp must be >= --start-tp."
        )


    if args.threads < 1:

        raise ValueError(
            "--threads must be at least 1."
        )


    if not 0 < args.alpha < 1:

        raise ValueError(
            "--alpha must be between 0 and 1."
        )


    # --------------------------------------------------------
    # Expected annotation directories from Step 08
    # --------------------------------------------------------

    intergenic_dir = os.path.join(
        input_dir,
        "intergenic"
    )


    variable3_dir = os.path.join(
        input_dir,
        "variable_3prime"
    )


    if not os.path.isdir(
        intergenic_dir
    ):

        raise FileNotFoundError(
            "Intergenic directory does not exist:\n"
            f"{intergenic_dir}"
        )


    if not os.path.isdir(
        variable3_dir
    ):

        raise FileNotFoundError(
            "Variable 3' directory does not exist:\n"
            f"{variable3_dir}"
        )


    # --------------------------------------------------------
    # Print configuration
    # --------------------------------------------------------

    print("========================================")
    print("HELIOS NAD-Seq: Step 09 - DESeq2 stats")
    print("========================================")

    print(
        f"Count-table directory: {input_dir}"
    )

    print(
        f"Time points:           "
        f"tp{args.start_tp}-tp{args.end_tp}"
    )

    print(
        f"CPUs:                  "
        f"{args.threads}"
    )

    print(
        f"Alpha:                 "
        f"{args.alpha}"
    )

    print(
        "Annotations:"
    )

    print(
        "  intergenic"
    )

    print(
        "  variable_3prime"
    )

    print("========================================")


    # ========================================================
    # Intergenic
    # ========================================================

    intergenic_processed, intergenic_skipped = (
        process_annotation(
            annotation_name="intergenic",
            annotation_dir=intergenic_dir,
            start_tp=args.start_tp,
            end_tp=args.end_tp,
            threads=args.threads,
            alpha=args.alpha
        )
    )


    # ========================================================
    # Variable 3'
    # ========================================================

    variable3_processed, variable3_skipped = (
        process_annotation(
            annotation_name="variable_3prime",
            annotation_dir=variable3_dir,
            start_tp=args.start_tp,
            end_tp=args.end_tp,
            threads=args.threads,
            alpha=args.alpha
        )
    )


    # --------------------------------------------------------
    # Final summary
    # --------------------------------------------------------

    print()
    print("========================================")
    print("Step 09 completed.")
    print("----------------------------------------")

    print(
        f"Intergenic processed/existing: "
        f"{intergenic_processed}"
    )

    print(
        f"Intergenic skipped:            "
        f"{intergenic_skipped}"
    )

    print(
        f"Variable 3' processed/existing:"
        f" {variable3_processed}"
    )

    print(
        f"Variable 3' skipped:           "
        f"{variable3_skipped}"
    )

    print("========================================")


if __name__ == "__main__":
    main()
