#!/usr/bin/env python3

import argparse
import os
import pandas as pd


def main():

    parser = argparse.ArgumentParser(
        description=(
            "Filter PyDESeq2 results for significantly enriched "
            "HELIOS NAD-Seq genes at each time point."
        )
    )

    parser.add_argument(
        "input_dir",
        help=(
            "Directory containing tp1, tp2, ... subdirectories "
            "with *_results.csv files generated by Step 09."
        )
    )

    parser.add_argument(
        "--start-tp",
        type=int,
        default=1,
        help="First time point to process. Default: 1."
    )

    parser.add_argument(
        "--end-tp",
        type=int,
        default=16,
        help="Last time point to process. Default: 16."
    )

    parser.add_argument(
        "--padj",
        type=float,
        default=0.05,
        help="Adjusted p-value threshold. Default: 0.05."
    )

    parser.add_argument(
        "--log2fc",
        type=float,
        default=1.0,
        help="Minimum log2 fold-change threshold. Default: 1."
    )

    args = parser.parse_args()


    # --------------------------------------------------------
    # Validate input
    # --------------------------------------------------------

    input_dir = os.path.abspath(args.input_dir)

    if not os.path.isdir(input_dir):
        raise FileNotFoundError(
            f"Input directory does not exist: {input_dir}"
        )

    if args.start_tp > args.end_tp:
        raise ValueError(
            "--start-tp must be smaller than or equal to --end-tp."
        )

    if not 0 < args.padj <= 1:
        raise ValueError(
            "--padj must be greater than 0 and <= 1."
        )


    print("========================================")
    print("HELIOS NAD-Seq: Step 10 - Filter genes")
    print("========================================")
    print(f"Input directory: {input_dir}")
    print(
        f"Time points:     "
        f"tp{args.start_tp}-tp{args.end_tp}"
    )
    print(f"padj threshold:  < {args.padj}")
    print(f"log2FC threshold: >= {args.log2fc}")
    print("========================================")


    processed = 0
    skipped = 0
    total_significant = 0


    # ========================================================
    # Process each time point
    # ========================================================

    for tp in range(
        args.start_tp,
        args.end_tp + 1
    ):

        tp_name = f"tp{tp}"

        tp_dir = os.path.join(
            input_dir,
            tp_name
        )


        if not os.path.isdir(tp_dir):

            print(
                f"[{tp_name}] Directory not found, skipping."
            )

            skipped += 1
            continue


        # ----------------------------------------------------
        # Find Step 09 results file
        # ----------------------------------------------------

        result_files = sorted(
            [
                filename
                for filename in os.listdir(tp_dir)
                if filename.endswith("_results.csv")
            ]
        )


        if not result_files:

            print(
                f"[{tp_name}] No *_results.csv file found, "
                "skipping."
            )

            skipped += 1
            continue


        if len(result_files) > 1:

            raise RuntimeError(
                f"[{tp_name}] More than one *_results.csv "
                f"file found: {result_files}"
            )


        results_file = result_files[0]

        results_path = os.path.join(
            tp_dir,
            results_file
        )


        print()
        print("----------------------------------------")
        print(f"[{tp_name}] Processing:")
        print(f"        {results_path}")


        # ----------------------------------------------------
        # Read DESeq2 results
        # ----------------------------------------------------

        df = pd.read_csv(
            results_path,
            index_col=0
        )


        # ----------------------------------------------------
        # Check required columns
        # ----------------------------------------------------

        required_columns = {
            "log2FoldChange",
            "padj"
        }

        missing_columns = (
            required_columns
            - set(df.columns)
        )


        if missing_columns:

            raise ValueError(
                f"[{tp_name}] Missing required columns: "
                f"{', '.join(sorted(missing_columns))}"
            )


        # ----------------------------------------------------
        # Remove rows where padj or log2FC is missing
        # ----------------------------------------------------

        valid_df = df.dropna(
            subset=[
                "padj",
                "log2FoldChange"
            ]
        )


        # ----------------------------------------------------
        # Apply significance thresholds
        # ----------------------------------------------------

        significant_df = valid_df[
            (valid_df["padj"] < args.padj)
            &
            (
                valid_df["log2FoldChange"]
                >= args.log2fc
            )
        ].copy()


        # ----------------------------------------------------
        # Sort most significant genes first
        # ----------------------------------------------------

        significant_df = significant_df.sort_values(
            by=[
                "padj",
                "log2FoldChange"
            ],
            ascending=[
                True,
                False
            ]
        )


        # ----------------------------------------------------
        # Output filename
        # ----------------------------------------------------

        output_name = results_file.replace(
            "_results.csv",
            "_significant.csv"
        )

        output_path = os.path.join(
            tp_dir,
            output_name
        )


        significant_df.to_csv(
            output_path,
            index=True
        )


        n_total = len(df)
        n_valid = len(valid_df)
        n_significant = len(significant_df)


        print(
            f"Total tested features:   {n_total}"
        )

        print(
            f"Features with valid padj: {n_valid}"
        )

        print(
            f"Significant genes:       {n_significant}"
        )

        print(
            f"Saved:"
        )

        print(
            f"        {output_path}"
        )


        total_significant += n_significant
        processed += 1


    # ========================================================
    # Summary
    # ========================================================

    print()
    print("========================================")
    print("Step 10 completed.")
    print(f"Processed time points: {processed}")
    print(f"Skipped time points:   {skipped}")
    print(
        f"Total significant gene-timepoint hits: "
        f"{total_significant}"
    )
    print("========================================")


if __name__ == "__main__":
    main()
